---
- hosts: docker-server
  become: true
  vars:
    linux_user: ramsgcp23
    docker_user: rama
  vars_files:
    - secret_vars.yaml
  tasks:
  - name: Update apt package cache
    ansible.builtin.apt:
      update_cache: yes
  - name: Install Docker
    ansible.builtin.apt:
      name: docker.io
      state: present
  - name: Add user '{{ linux_user }}' to the docker group
    ansible.builtin.user:
      name: '{{ linux_user }}'
      groups: docker
      append: yes
  - name: Set permissions on /var/run/docker.sock
    ansible.builtin.file:
      path: /var/run/docker.sock
      mode: '0777'
  - name: Create user '{{ docker_user}}' # adduser maha
    ansible.builtin.user:
      name: '{{ docker_user}}'
      createhome: yes
      shell: /bin/bash
      system: no  # Set to 'no' to create a regular user
      state: present
  - name: Set the password for user '{{ docker_user}}'
    ansible.builtin.user:
      name: '{{ docker_user}}'
      password: "{{ docker_user_password | password_hash('sha512') }}"
  - name: Enable password authentication in SSH
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PasswordAuthentication'
      line: 'PasswordAuthentication yes'
      backup: yes
  - name: Restart SSH service
    ansible.builtin.service:
      name: ssh
      state: restarted
  - name: Add 'maha' to the sudoers file
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      insertafter: EOF
      line: 'maha ALL=(ALL:ALL) ALL'
      validate: 'visudo -cf %s'