---
- hosts: jenkins-slave
  become: yes
  tasks:
    - name: Updating the Registry
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install java for slave
      apt: 
        name: openjdk-11-jre
        state: present
    - name: Create a home directory for jenkins in slave
      file:
        path: /home/ramsgcp23/jenkins
        state: directory
        mode: '0755'
        owner: ramsgcp23
        group: ramsgcp23
    - name: Donwload the JAVA package
      ansible.builtin.get_url:
        url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
        dest: /opt/
    - name: extracting the JAVA
      ansible.builtin.unarchive:
        src: /opt/openjdk-17.0.2_linux-x64_bin.tar.gz
        dest: /opt
        remote_src: yes
    - name: Download MVN package
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
        dest: /opt/
    - name: Extract MVN package 
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.8.8-bin.tar.gz
        dest: /opt
        remote_src: yes